# Generated by Django 3.2.8 on 2021-11-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
