# Generated by Django 3.2.8 on 2021-11-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20211121_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, to='posts.Image'),
        ),
    ]
